import { createClient } from "npm:@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type, x-backup-secret, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

// ============================================================
// Correções necessárias no DDL gerado pelas RPCs
//
// Causa raiz: as RPCs geram DDL com search_path vazio ('')
// sem qualificar os objetos que elas mesmas referenciam.
// Além disso, as políticas RLS saem com sintaxe inválida de roles.
//
// As correções abaixo replicam em TypeScript o mesmo conjunto
// de transformações do script Python script-correção-ddl-lovable.py.
// ============================================================
function fixDdl(content: string, realTables: Set<string>): string {
  // Passo 2 — {public} e {authenticated} sem chaves nas policies
  content = content.replaceAll(" TO {public} ", " TO public ");
  content = content.replaceAll(" TO {authenticated} ", " TO authenticated ");

  // Passos 3 + 4 — app_role sem schema em assinaturas de função e na tabela user_roles
  const lines = content.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];

    const isFunctionLine =
      line.includes("CREATE OR REPLACE FUNCTION") || line.includes("ALTER FUNCTION") || line.includes("GRANT");

    if (isFunctionLine && line.includes("app_role")) {
      lines[i] = line.replaceAll("_role app_role", "_role public.app_role");
      continue;
    }

    if (
      line.includes("role app_role") &&
      !line.includes("FUNCTION") &&
      !line.includes("GRANT") &&
      !line.trimStart().startsWith("--")
    ) {
      lines[i] = line
        .replaceAll("role app_role", "role public.app_role")
        .replaceAll("'user'::app_role", "'user'::public.app_role");
    }
  }
  content = lines.join("\n");

  // Passo 5 — casts ::app_role sem schema nos corpos das policies
  content = content.replace(/'(admin|user|moderator)'::app_role\b/g, "'$1'::public.app_role");

  // Passo 6 — FROM user_roles sem schema nas subqueries das policies
  content = content.replaceAll("FROM user_roles\n", "FROM public.user_roles\n");

  // Passos 7, 8, 9, 10 — qualificação linha a linha
  const lines2 = content.split("\n");
  let inView = false;

  for (let i = 0; i < lines2.length; i++) {
    let line = lines2[i];

    // Passo 7 — tabelas sem schema nas VIEWs
    if (/^CREATE OR REPLACE VIEW/.test(line)) inView = true;
    if (inView && line.trim() === ";") inView = false;

    if (inView) {
      line = line.replace(/\b(FROM|JOIN)([\s(]+)([a-z_][a-z_0-9]*)(?=[\s,)(]|$)/g, (_match, kw, sp, tbl) =>
        realTables.has(tbl) ? `${kw}${sp}public.${tbl}` : `${kw}${sp}${tbl}`,
      );
    }

    // Passo 8 — REFERENCES sem schema nas FKs
    line = line.replace(/\bREFERENCES (?!public\.|auth\.)([a-z_][a-z_0-9]*)\(/g, "REFERENCES public.$1(");

    // Passo 9 — EXECUTE FUNCTION sem schema nos triggers
    line = line.replace(/\bEXECUTE FUNCTION (?!public\.)([a-z_][a-z_0-9]*)\(/g, "EXECUTE FUNCTION public.$1(");

    // Passo 10 — has_role( sem schema nas policies
    if (line.includes("has_role(") && !line.trimStart().startsWith("--")) {
      line = line.replace(/(?<!public\.)has_role\(/g, "public.has_role(");
    }

    lines2[i] = line;
  }

  return lines2.join("\n");
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  const secret = req.headers.get("x-backup-secret");
  if (secret !== Deno.env.get("BACKUP_SECRET")) {
    return new Response("Unauthorized", { status: 401 });
  }

  try {
    const supabase = createClient(Deno.env.get("SUPABASE_URL")!, Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);

    const url = new URL(req.url);
    const schemaFilter = url.searchParams.get("schema") || "public";

    const ddl: string[] = [];

    ddl.push("--");
    ddl.push("-- PostgreSQL database dump (schema-only)");
    ddl.push("--");
    ddl.push(`-- Generated by export-schema-ddl edge function`);
    ddl.push(`-- Generated at: ${new Date().toISOString()}`);
    ddl.push(`-- Schema: ${schemaFilter}`);
    ddl.push("--");
    ddl.push("");
    ddl.push("SET statement_timeout = 0;");
    ddl.push("SET lock_timeout = 0;");
    ddl.push("SET idle_in_transaction_session_timeout = 0;");
    ddl.push("SET client_encoding = 'UTF8';");
    ddl.push("SET standard_conforming_strings = on;");
    ddl.push("SELECT pg_catalog.set_config('search_path', '', false);");
    ddl.push("SET check_function_bodies = false;");
    ddl.push("SET xmloption = content;");
    ddl.push("SET client_min_messages = warning;");
    ddl.push("SET row_security = off;");
    ddl.push("");

    // ============================================================
    // 1. EXTENSIONS
    // ============================================================
    const { data: extensions } = await supabase.rpc("export_ddl_extensions" as any);
    if (extensions) {
      for (const ext of extensions as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${ext.extname}; Type: EXTENSION; Schema: -; Owner: -`);
        ddl.push("--");
        ddl.push("");
        ddl.push(
          `CREATE EXTENSION IF NOT EXISTS ${ext.extname === "uuid-ossp" ? '"uuid-ossp"' : ext.extname} WITH SCHEMA ${ext.schema_name};`,
        );
        ddl.push("");
        ddl.push("");
      }
    }

    // ============================================================
    // 2. ENUMS / TYPES
    // ============================================================
    const { data: enums } = await supabase.rpc("export_ddl_enums" as any, { p_schema: schemaFilter });
    if (enums) {
      for (const e of enums as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${e.type_name}; Type: TYPE; Schema: ${schemaFilter}; Owner: postgres`);
        ddl.push("--");
        ddl.push("");
        ddl.push(`CREATE TYPE ${schemaFilter}.${e.type_name} AS ENUM (`);
        const labels = e.enum_labels as string[];
        for (let i = 0; i < labels.length; i++) {
          ddl.push(`    '${labels[i]}'${i < labels.length - 1 ? "," : ""}`);
        }
        ddl.push(");");
        ddl.push("");
        ddl.push("");
        ddl.push(`ALTER TYPE ${schemaFilter}.${e.type_name} OWNER TO postgres;`);
        ddl.push("");
      }
    }

    // ============================================================
    // 3. FUNCTIONS
    // ============================================================
    const { data: functions } = await supabase.rpc("export_ddl_functions" as any, { p_schema: schemaFilter });
    if (functions) {
      for (const fn of functions as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${fn.function_signature}; Type: FUNCTION; Schema: ${schemaFilter}; Owner: postgres`);
        ddl.push("--");
        ddl.push("");
        ddl.push(fn.function_def);
        ddl.push("");
        ddl.push("");
        ddl.push(`ALTER FUNCTION ${fn.full_signature} OWNER TO postgres;`);
        ddl.push("");
      }
    }

    // ============================================================
    // 4. TABLES
    // ============================================================
    ddl.push("SET default_tablespace = '';");
    ddl.push("");
    ddl.push("SET default_table_access_method = heap;");
    ddl.push("");

    const { data: tables } = await supabase.rpc("export_ddl_tables" as any, { p_schema: schemaFilter });
    if (tables) {
      for (const tbl of tables as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${tbl.table_name}; Type: TABLE; Schema: ${schemaFilter}; Owner: postgres`);
        ddl.push("--");
        ddl.push("");
        ddl.push(tbl.create_ddl);
        ddl.push("");
        ddl.push("");
        ddl.push(`ALTER TABLE ${schemaFilter}.${tbl.table_name} OWNER TO postgres;`);
        ddl.push("");

        if (tbl.table_comment) {
          ddl.push("--");
          ddl.push(`-- Name: TABLE ${tbl.table_name}; Type: COMMENT; Schema: ${schemaFilter}; Owner: postgres`);
          ddl.push("--");
          ddl.push("");
          ddl.push(`COMMENT ON TABLE ${schemaFilter}.${tbl.table_name} IS '${tbl.table_comment.replace(/'/g, "''")}';`);
          ddl.push("");
          ddl.push("");
        }
      }
    }

    // ============================================================
    // 5. VIEWS
    // ============================================================
    const { data: views } = await supabase.rpc("export_ddl_views" as any, { p_schema: schemaFilter });
    if (views) {
      for (const v of views as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${v.view_name}; Type: VIEW; Schema: ${schemaFilter}; Owner: postgres`);
        ddl.push("--");
        ddl.push("");
        ddl.push(v.view_def);
        ddl.push("");
        ddl.push("");
        ddl.push(`ALTER VIEW ${schemaFilter}.${v.view_name} OWNER TO postgres;`);
        ddl.push("");

        if (v.view_comment) {
          ddl.push("--");
          ddl.push(`-- Name: VIEW ${v.view_name}; Type: COMMENT; Schema: ${schemaFilter}; Owner: postgres`);
          ddl.push("--");
          ddl.push("");
          ddl.push(`COMMENT ON VIEW ${schemaFilter}.${v.view_name} IS '${v.view_comment.replace(/'/g, "''")}';`);
          ddl.push("");
          ddl.push("");
        }
      }
    }

    // ============================================================
    // 6. SEQUENCES
    // ============================================================
    const { data: sequences } = await supabase.rpc("export_ddl_sequences" as any, { p_schema: schemaFilter });
    if (sequences) {
      for (const seq of sequences as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${seq.sequence_name}; Type: SEQUENCE; Schema: ${schemaFilter}; Owner: postgres`);
        ddl.push("--");
        ddl.push("");
        ddl.push(seq.sequence_ddl);
        ddl.push("");
        ddl.push("");
      }
    }

    // ============================================================
    // 7. CONSTRAINTS (PK + UNIQUE)
    // ============================================================
    const { data: constraints } = await supabase.rpc("export_ddl_constraints" as any, { p_schema: schemaFilter });
    if (constraints) {
      for (const c of constraints as any[]) {
        ddl.push("--");
        ddl.push(
          `-- Name: ${c.table_name} ${c.constraint_name}; Type: CONSTRAINT; Schema: ${schemaFilter}; Owner: postgres`,
        );
        ddl.push("--");
        ddl.push("");
        ddl.push(c.constraint_ddl);
        ddl.push("");
        ddl.push("");
      }
    }

    // ============================================================
    // 8. INDEXES
    // ============================================================
    const { data: indexes } = await supabase.rpc("export_ddl_indexes" as any, { p_schema: schemaFilter });
    if (indexes) {
      for (const idx of indexes as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${idx.index_name}; Type: INDEX; Schema: ${schemaFilter}; Owner: postgres`);
        ddl.push("--");
        ddl.push("");
        ddl.push(idx.index_ddl);
        ddl.push("");
        ddl.push("");
      }
    }

    // ============================================================
    // 9. FOREIGN KEYS  (antes dos triggers — passo 11 da correção)
    // ============================================================
    const { data: fkeys } = await supabase.rpc("export_ddl_foreign_keys" as any, { p_schema: schemaFilter });
    if (fkeys) {
      for (const fk of fkeys as any[]) {
        ddl.push("--");
        ddl.push(
          `-- Name: ${fk.table_name} ${fk.constraint_name}; Type: FK CONSTRAINT; Schema: ${schemaFilter}; Owner: postgres`,
        );
        ddl.push("--");
        ddl.push("");
        ddl.push(fk.fk_ddl);
        ddl.push("");
        ddl.push("");
      }
    }

    // ============================================================
    // 10. TRIGGERS  (depois das FKs — passo 11 da correção)
    // ============================================================
    const { data: triggers } = await supabase.rpc("export_ddl_triggers" as any, { p_schema: schemaFilter });
    if (triggers) {
      for (const tr of triggers as any[]) {
        ddl.push("--");
        ddl.push(
          `-- Name: ${tr.table_name} ${tr.trigger_name}; Type: TRIGGER; Schema: ${schemaFilter}; Owner: postgres`,
        );
        ddl.push("--");
        ddl.push("");
        ddl.push(tr.trigger_ddl);
        ddl.push("");
        ddl.push("");
      }
    }

    // ============================================================
    // 11. RLS ENABLE + POLICIES
    // ============================================================
    const { data: rlsEnable } = await supabase.rpc("export_ddl_rls_enable" as any, { p_schema: schemaFilter });
    if (rlsEnable) {
      for (const r of rlsEnable as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${r.table_name}; Type: ROW SECURITY; Schema: ${schemaFilter}; Owner: postgres`);
        ddl.push("--");
        ddl.push("");
        ddl.push(`ALTER TABLE ${schemaFilter}.${r.table_name} ENABLE ROW LEVEL SECURITY;`);
        ddl.push("");
        ddl.push("");
      }
    }

    const { data: policies } = await supabase.rpc("export_ddl_policies" as any, { p_schema: schemaFilter });
    if (policies) {
      for (const p of policies as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${p.table_name} ${p.policy_name}; Type: POLICY; Schema: ${schemaFilter}; Owner: postgres`);
        ddl.push("--");
        ddl.push("");
        ddl.push(p.policy_ddl);
        ddl.push("");
        ddl.push("");
      }
    }

    // ============================================================
    // 12. COLUMN COMMENTS
    // ============================================================
    const { data: colComments } = await supabase.rpc("export_ddl_column_comments" as any, { p_schema: schemaFilter });
    if (colComments) {
      for (const cc of colComments as any[]) {
        ddl.push("--");
        ddl.push(
          `-- Name: COLUMN ${cc.table_name}.${cc.column_name}; Type: COMMENT; Schema: ${schemaFilter}; Owner: postgres`,
        );
        ddl.push("--");
        ddl.push("");
        ddl.push(cc.comment_ddl);
        ddl.push("");
        ddl.push("");
      }
    }

    // ============================================================
    // 13. GRANTS (ACLs)
    // ============================================================
    const { data: grants } = await supabase.rpc("export_ddl_grants" as any, { p_schema: schemaFilter });
    if (grants) {
      for (const g of grants as any[]) {
        ddl.push("--");
        ddl.push(`-- Name: ${g.object_type} ${g.object_name}; Type: ACL; Schema: ${schemaFilter}; Owner: postgres`);
        ddl.push("--");
        ddl.push("");
        ddl.push(g.grant_ddl);
        ddl.push("");
        ddl.push("");
      }
    }

    ddl.push("--");
    ddl.push("-- PostgreSQL database dump complete");
    ddl.push("--");

    // ============================================================
    // Passos 2–10: aplicar todas as correções de qualificação de
    // schema no DDL montado antes de devolvê-lo ao chamador.
    // O conjunto realTables é derivado do próprio DDL gerado acima,
    // garantindo que só tabelas reais sejam qualificadas nas views.
    // ============================================================
    const rawContent = ddl.join("\n");
    const realTables = new Set([...rawContent.matchAll(/CREATE TABLE public\.([a-z_0-9]+)/g)].map((m) => m[1]));
    const fixedContent = fixDdl(rawContent, realTables);

    return new Response(fixedContent, {
      headers: {
        ...corsHeaders,
        "Content-Type": "text/plain; charset=utf-8",
        "Content-Disposition": `attachment; filename="schema-ddl-${new Date().toISOString().replace(/[:.]/g, "-")}.sql"`,
      },
    });
  } catch (error) {
    console.error("EXPORT DDL ERROR:", error);
    return new Response(JSON.stringify({ success: false, error: String(error) }), {
      status: 500,
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
